# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write # Необходимо для JamesIves/github-pages-deploy-action
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -la
          echo "Checking dist directory:"
          ls -la ./dist || echo "dist directory does not exist"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages # Ветка, в которую будет делаться деплой
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true # Очищает ветку gh-pages перед деплоем
